// Words List
// eslint-disable-next-line import/prefer-default-export
export const WORDS = 'GUITARRA/BATERIA/TRIANGULO/BAJO/TRIPLE/TAMBORES/REDOBLE/SAXOFON/CAJA/BONGOES/FLAUTA/ACORDEON/TROMPETA/TROMBON/VIOLIN/VIOLONCHELO/TIMBAL/PIANO/CONTRABAJO/MARACAS';

export const ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';
