// Words List
export const WORDS = 'GUITARRA/BATERIA/TRIANGULO/BAJO/TRIPLE/TAMBORES/REDOBLE/SAXOFON/CAJA/BONGOES/FLAUTA/ACORDEON/TROMPETA/TROMBON/VIOLIN/VIOLONCHELO/TIMBAL/PIANO/CONTRABAJO/MARACAS';

// Alphabet to random letters
export const ALPHABET = 'ABCDEFGHIJKLMNÑOPQRSTUVWXYZ';

// Direction to random
export const DIRECTION = 'HV';
